### ISSUE TITLE
Lazyloading

### ISSUE THREAD

**Issue by tushariscoolster** [driftyco/cordova-camera-roll#1]
i want to implement lazy loading in this. for eg:-i want image from 1-25; on next request i want from 25-50;like pagination

**Comment by Ionitron** [comment]
Greetings @tushariscoolster!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
