### ISSUE TITLE
Some asset image urls are not loading

### ISSUE THREAD

**Issue by kodypeterson** [driftyco/cordova-camera-roll#2]
I am getting all the image urls back from the plugin. But a good amount of them do not load when showing a large list of images. Any ideas?

**Comment by Ionitron** [comment]
Greetings @kodypeterson!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
