### ISSUE TITLE
http support

### ISSUE THREAD

**Issue by Hirbod** [driftyco/cordova-camera-roll#4]
Please add support for storing images trough http/https

**Comment by Ionitron** [comment]
Greetings @Hirbod!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
